import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export function useSubjects() {
  const { profile } = useAuth();
  return useQuery({
    queryKey: ["subjects", profile?.branch, profile?.section],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("subjects")
        .select("*")
        .eq("branch", profile!.branch!)
        .eq("section", profile!.section!)
        .order("name");
      if (error) throw error;
      return data;
    },
    enabled: !!profile?.branch && !!profile?.section,
  });
}

export function useCreateSubject() {
  const qc = useQueryClient();
  const { user } = useAuth();
  return useMutation({
    mutationFn: async ({ name, branch, section }: { name: string; branch: string; section: string }) => {
      // join_code is auto-generated by DB trigger; pass empty string to satisfy types
      const { error } = await supabase.from("subjects").insert({
        name,
        branch,
        section,
        created_by: user!.id,
        join_code: "",
      } as any);
      if (error) throw error;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["subjects"] }),
  });
}
